---
# Source: kai/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anchore-kai
  labels:
    helm.sh/chart: kai-0.3.0
    app.kubernetes.io/name: kai
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.3.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: kai/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-kai
  labels:
    app: RELEASE-NAME-kai
    chart: kai-0.3.0
    release: RELEASE-NAME
    heritage: Helm
type: Opaque
stringData:
  KAI_ANCHORE_PASSWORD: foobar
---
# Source: kai/templates/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: RELEASE-NAME-kai
  labels:
    app: RELEASE-NAME-kai
    chart: kai-0.3.0
    release: RELEASE-NAME
    heritage: Helm
data:
  .kai.yaml: |
    kubeconfig:
      path: use-in-cluster
      cluster: docker-desktop
    output: json
    quiet: false
    log:
      structured: false
      level: debug
      file: 
    namespaces:
      null
    namespace-selectors:
      exclude: []
      include: []
    mode: periodic
    polling-interval-seconds: 60
    kubernetes-request-timeout-seconds: 
    kubernetes:
      request-timeout-seconds: 60
      request-batch-size: 100
      worker-pool-size: 100
    ignore-not-running: true
    missing-tag-policy:
      policy: digest
      tag: UNKNOWN
    anchore:
      url: 
      user: admin
      password: $KAI_ANCHORE_PASSWORD
      account: admin
      http:
        insecure: true
        timeout-seconds: 10
---
# Source: kai/templates/cluster-role-readonly.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kai-read-only
rules:
- apiGroups: [""]
  resources: ["pods","namespaces"]
  verbs: ["get", "watch", "list"]
---
# Source: kai/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kai-read-only-binding
subjects:
  - kind: ServiceAccount
    name: anchore-kai
    namespace: default
roleRef:
  kind: ClusterRole
  name: kai-read-only
  apiGroup: rbac.authorization.k8s.io
---
# Source: kai/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-kai
  labels:
    helm.sh/chart: kai-0.3.0
    app.kubernetes.io/name: kai
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kai
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: kai/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-kai
  labels:
    helm.sh/chart: kai-0.3.0
    app.kubernetes.io/name: kai
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kai
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      annotations:
        checksum/config: 3a4529db453847d7c33ee76dc40a42746d07ad4c5eab29a11f76740afeee9047
      labels:
        app.kubernetes.io/name: kai
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: anchore-kai
      securityContext:
        {}
      containers:
        - name: kai
          securityContext:
            {}
          image: "anchore/kai:v0.3.0"
          imagePullPolicy: IfNotPresent
          command: ["kai"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - kai
                - version
            initialDelaySeconds: 1
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - kai
                - version
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
          resources:
            {}
          volumeMounts:
            - name: config-volume
              mountPath: /home/nonroot/.kai.yaml
              subPath: .kai.yaml
          envFrom:
            - secretRef:
                name: RELEASE-NAME-kai
      volumes:
        - name: config-volume
          configMap:
            name: RELEASE-NAME-kai
